# 2.1 Data Manipulation

Apache MXNet是一个开源深度学习软件框架，用于训练及部署深度神经网络。本节将介绍如何使用 MXNet 提供的 NDArray 类来处理数据。如果你之前用过 NumPy，你会发现 MXNet 的 NDArray 和 NumPy 的多维数组非常类似。然而，NDArray 提供更多的功能，例如在 GPU 上计算。

In [79]:
from mxnet import np, npx
npx.set_np()    # 启用这个模式后，MXNet 的 ndarray 行为将更加类似于 NumPy 的 ndarray，包括支持大部分 NumPy 的接口和操作。这样可以使开发人员在从 NumPy 迁移到 MXNet 时更加方便，并且可以利用 MXNet 提供的 GPU 加速等高级功能。

## 2.1.1 创建 NDArray

In [80]:
x = np.arange(12)   # 可以使用 arange 创建一个行向量, 默认创建为浮点数
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [81]:
x.shape # shape属性来访问 NDArray 对象的形状

(12,)

In [82]:
x.size # size属性来访问 NDArray 对象的大小

12

In [83]:
X = x.reshape(3, 4) # 通过 reshape 函数把向量 x 的形状改为 (3, 4)
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [84]:
np.zeros((2, 3, 4)) # 创建一个形状为 (2, 3, 4) 的张量，其中所有元素都是 0

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [85]:
np.ones((3, 4)) # 创建一个形状为 (3, 4) 的张量，其中所有元素都是 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
np.random.normal(0, 1, size=(3, 4)) # 创建一个形状为 (3, 4) 的张量，其中所有元素都是从均值为 0 标准差为 1 的正态分布中随机采样的

array([[-0.59164983, -0.7882176 ,  0.8586049 ,  0.7417728 ],
       [-0.22794184, -1.4734439 ,  0.20131476, -1.0730928 ],
       [ 0.35005474, -1.0424827 ,  0.5360521 , -1.3278849 ]])

In [87]:
np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]) # 通过 Python 的列表（list）指定需要创建的 NDArray 中的元素

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

## 2.1.2. Indexing and Slicing
索引和切片: 与任何Python数组一样：第一个元素的索引是0，最后一个元素索引是-1； 可以指定范围以包含第一个元素和最后一个之前的元素

In [88]:
X, X[-1], X[1:3]    # X[-1] 是最后一个元素，X[1:3] 是第二个和第三个元素

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([ 8.,  9., 10., 11.]),
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]))

In [89]:
# 除读取外，我们还可以通过指定索引来将元素写入矩阵。
X[1, 2] = 9 # 将索引为 (1, 2) (第二行,第三个) 的元素替换为 9
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]])

In [90]:
# 如果我们想为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值
X[0:2, :] = 12 # 将第一行和第二行的所有元素替换为 12
X

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]])

## 2.1.3. Operations
运算符
我们可以在这些数据上执行数学运算，其中最简单且最有用的操作是按元素（elementwise）运算。 
它们将标准标量运算符应用于数组的每个元素。 对于将两个数组作为输入的函数，按元素运算将二元运算符应用于两个数组中的每对位置对应的元素。 我们可以基于任何从标量到标量的函数来创建按元素函数。
在数学表示法中，我们将通过符号 $f: \mathbb{R} \rightarrow \mathbb{R}$ 表一元标量运算符（只接收一个输入）
同样，我们通过符号 $f: \mathbb{R}, \mathbb{R} \rightarrow \mathbb{R}$ 表示二元标量运算符，这意味着该函数接收两个输入，并产生一个输出。 
给定同一形状的任意两个向量 $u$ 和 $v$，我们可以通过符号 $f$ 得到一个向量 $z$，其中 $z_i = f(u_i, v_i)$。


In [91]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # 按元素运算

(array([ 3.,  4.,  6., 10.]),
 array([-1.,  0.,  2.,  6.]),
 array([ 2.,  4.,  8., 16.]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1.,  4., 16., 64.]))

In [92]:
np.exp(x)   # 按元素计算指数函数

array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03])

In [93]:
# 我们可以把多个 NDArray 合并（concatenate）。只需要提供一个 NDArray 列表，并给定需要连接的轴的编号
X = np.arange(12).reshape(3, 4)
Y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y, np.concatenate([X, Y], axis=0), np.concatenate([X, Y], axis=1)  # 沿行和列连接两个矩阵

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [94]:
# 可以通过逻辑运算符构建二元 NDArray
X == Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [95]:
X.sum() # NDArray 中的所有元素的和

array(66.)

## 2.1.4. Broadcasting
广播机制
在上面的部分中，我们看到了如何在相同形状的两个张量上执行按元素操作。 在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。 
这种机制的工作方式如下：
 1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
 2. 对生成的数组执行按元素操作。

In [96]:
# 在大多数情况下，我们将沿着数组中长度为1的轴进行广播
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)
a, b

(array([[0.],
        [1.],
        [2.]]),
 array([[0., 1.]]))

由于a和b分别是$3\times1$和$1\times2$矩阵，如果让它们相加，它们的形状不匹配。 我们将两个矩阵广播为一个更大的$3\times2$矩阵：
如下代码, 矩阵a将复制列， 矩阵b将复制行，然后再按元素相加。

In [97]:
a + b   # 广播机制

array([[0., 1.],
       [1., 2.],
       [2., 3.]])

In [98]:
# 以下代码等价于 a + b
np.broadcast_to(a, (3, 2)), np.broadcast_to(b, (3, 2)), np.broadcast_to(a, (3, 2)) + np.broadcast_to(b, (3, 2))

(array([[0., 0.],
        [1., 1.],
        [2., 2.]]),
 array([[0., 1.],
        [0., 1.],
        [0., 1.]]),
 array([[0., 1.],
        [1., 2.],
        [2., 3.]]))

# 2.1.5 Saving Memory 减少内存
运行一些操作可能会导致为新结果分配内存。 例如，如果我们用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的NDArray。
在下面的例子中，我们用Python的id()函数演示了这一点，它给我们提供了内存中引用对象的确切地址。 运行Y = Y + X后，我们会发现id(Y)指向另一个位置。 
这在某些情况下是有用的，但通常我们希望避免这种情况，原因有两个：
1. 首先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。通常情况下，我们希望原地执行这些更新；
2. 如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

In [99]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [100]:
# 执行原地操作非常简单。 我们可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>
Z = np.zeros_like(Y) # 创建一个形状和 Y 一样，但是元素为 0 的张量
print('id(Z):', id(Z))
Z[:] = X + Y # 原地操作
print('id(Z):', id(Z))
X, Y, Z

id(Z): 140514024109616
id(Z): 140514024109616


(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]]),
 array([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]]))

# 2.1.6 Conversion to Other Python Objects 转换为其他 Python 对象
将深度学习框架mxnet定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。但是转换后的结果不共享内存。 
这个小的不便实际上是非常重要的：当在CPU或GPU上执行操作的时候， 如果Python的NumPy包也希望使用相同的内存块执行其他操作，人们不希望停下计算来等它。

In [101]:
A = X.asnumpy() # 将 MXNet NDArray 转换为 NumPy ndarray
B = np.array(A) # 将 NumPy ndarray 转换为 MXNet NDArray
type(A), type(B)

(numpy.ndarray, mxnet.numpy.ndarray)

In [102]:
# 要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数。
a = np.array([3.5])
a, a.item(), float(a), int(a)   # item() 返回一个 Python 标量, float() 返回浮点数, int() 返回整数

(array([3.5]), 3.5, 3.5, 3)